export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{margin:'0px',  backgroundColor:'#f5f5f5'}} >
        {children}</body>
    </html>
  )
}
