export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.scss'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='body' style={{backgroundColor:'rgb(242,244,245)'}}>{children}</body>
    </html>
  )
}
